//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [Serializable]
    [DataContract(IsReference = true)]
    public class Product : EntityBase
    {
        [DataMember]
        [Display(Name = "ID")]
        public Int32 ProductID { get; set; }

        [DataMember]
        [Display(Name = "Name")]
        public String Name { get; set; }

        [DataMember]
        [Display(Name = "Unit Price")]
        public Decimal UnitPrice { get; set; }

        [DataMember]
        [Display(Name = "Quantity")]
        public Decimal Quantity
        {
            get; set;
        }
    }
}
