//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiXe
    {
        public int id { get; set; }
        public string HoTen { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
